### ISSUE TITLE
WithBalancerName is deprecated

### ISSUE THREAD

**Issue by hagaidayan** [mbobakov/grpc-consul-resolver#11]
in grpc

**Comment by mbobakov** [comment]
@hagaidayan could you share a place in docs with me? I'm a little bit surprised because `WithBalancerName` is a 'new' way to pick up right balancer  https://github.com/grpc/grpc-go/blob/36f3126920fe326b7874e730e3cc26546186d8f0/examples/features/load_balancing/README.md

**Comment by kshamko** [comment]
`	grpcConn, err := grpc.Dial(statsAddr,
		grpc.WithInsecure(),
		grpc.WithDefaultServiceConfig(`{"loadBalancingConfig": [{"round_robin":{}}]}`),
	)`

this one might me a fix
