### ISSUE TITLE
parameters ignored.

### ISSUE THREAD

**Issue by Lukiya** [mbobakov/grpc-consul-resolver#30]
build.go, line19
`dsn := strings.Join([]string{schemeName + ":/", url.Authority, url.Endpoint}, "/")`

This will ignore all parameters.

Changed to dsn := url.URL.String() makes parameter works.

**Comment by mbobakov** [comment]
It fixed by https://github.com/mbobakov/grpc-consul-resolver/pull/33 
Please update
