### ISSUE TITLE
cannot use url.Endpoint (value of type func() string) as type string in array or slice literal

### ISSUE THREAD

**Issue by linqiurong** [mbobakov/grpc-consul-resolver#37]
go/pkg/mod/github.com/mbobakov/grpc-consul-resolver@v1.4.4/builder.go:20:65: cannot use url.Endpoint (value of type func() string) as type string in array or slice literal

**Comment by UpDownXH** [comment]
Same error

**Comment by Bruce-CodeMan** [comment]
Same Error

**Comment by Bruce-CodeMan** [comment]
> Same error
you can modify the builder.go file, 20: modify the url.Endpoint -> url.Endpoint(),that's ok!

**Comment by Bruce-CodeMan** [comment]
![image](https://user-images.githubusercontent.com/65518559/220369508-3919e68e-563a-4eda-8dea-59f846aea8f5.png)

**Comment by linqiurong** [comment]
upgrade google.golang.org/grpc  to v1.53.0

**Comment by radujipa** [comment]
Likely related to https://github.com/grpc/grpc-go/pull/5852/files#diff-732f365bd38694dea48332c13814847ee19a76bebc5f3d2c87733f1a4ee915ff as released in v1.5.3

**Comment by shiopuff** [comment]
Same error. 
Maybe you can REPLACE grpc-consul-resolver@v1.4.4/builder.go: 20  `url. Endpoint` with `url. Endpoint()`.
It works.

**Comment by mbobakov** [comment]
Sorry for delayed answer. It fixed https://github.com/mbobakov/grpc-consul-resolver/pull/33 
Please update.
