### ISSUE TITLE
The terminal keeps getting errors:ERROR: [Consul resolver] Couldn't update client connection. error={bad resolver state}

### ISSUE THREAD

**Issue by palp1tate** [mbobakov/grpc-consul-resolver#45]
Hi,help wanted!
I user [grpc-consul-resolver](https://github.com/mbobakov/grpc-consul-resolver) as below:
```go
package initialize

import (
	"fmt"

	_ "github.com/mbobakov/grpc-consul-resolver"
	"go.uber.org/zap"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	"cloudshop-api/user/global"
	"cloudshop-api/user/proto"
)

func InitServiceConn() {
	consul := global.ServerConfig.Consul
	userConn, err := grpc.Dial(
		fmt.Sprintf("consul://%s:%d/%s/?wait=14s", consul.Host, consul.Port, global.ServerConfig.Service.Name),
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithDefaultServiceConfig(`{"loadBalancingPolicy": "round_robin"}`),
	)
	if err != nil {
		zap.S().Fatal("fail to connect Service")
	}
	userServiceClient := proto.NewUserClient(userConn)
	global.UserServiceClient = userServiceClient
}
```
The code can run and the grpc service and http service can be registered，also they can pass the health check:
![image](https://github.com/mbobakov/grpc-consul-resolver/assets/120303802/9c5babcc-da7c-4938-87f3-0a73800c5e28)
But when the code is running, the terminal keeps showing  the error:ERROR: [Consul resolver] Couldn't update client connection. error={bad resolver state}
![image](https://github.com/mbobakov/grpc-consul-resolver/assets/120303802/e55e10d2-2247-4282-b912-cfcf13acd008)
As a result，I fail to call GRPC service，though my application can receive HTTP requests，which means Gin works well.

**Comment by palp1tate** [comment]
This error when I  call GRPC service:rpc error: code = Unavailable desc = last resolver error: produced zero addresses
version of some critical packages：
github.com/hashicorp/consul/api v1.25.1
google.golang.org/grpc v1.58.2
github.com/mbobakov/grpc-consul-resolver v1.5.2

**Comment by careerist-boy** [comment]
我也出现了这个问题，请问您解决这个问题了么？原因是什么？

**Comment by palp1tate** [comment]
> 我也出现了这个问题，请问您解决这个问题了么？原因是什么？
没找到服务，有服务没注册，健康检查不通过等等

**Comment by careerist-boy** [comment]
我的健康检查已经关闭了，服务注册的时候没有开启健康检查，不会影响报出这个问题吧？

**Comment by palp1tate** [comment]
> 我的健康检查已经关闭了，服务注册的时候没有开启健康检查，不会影响报出这个问题吧？

根本原因是找不到注册的服务，你可以在你的consul UI界面上看是否注册成功，我做项目的时候开启了健康检查，检查不过关，consul就会自动注销该服务，建议打开健康检查调试
