### ISSUE TITLE
Removal of tooling dependencies have not been released

### ISSUE THREAD

**Issue by radujipa** [mbobakov/grpc-consul-resolver#47]
Our automated dependency managers are still running into issues from this package due to tooling previously added to the go.mod which [has been since fixed](https://github.com/mbobakov/grpc-consul-resolver/pull/42).

Could we please have a release made of those changes such that we do not pin on a commit sha?

**Comment by radujipa** [comment]
@mbobakov ?

**Comment by mbobakov** [comment]
sorry for the delayed answer =( Released
